version: '3.12'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: 'your-openai-api-key'
      PINECONE_API_KEY: 'your-pinecone-api-key'
    volumes:
      - .:/app
